name: Go
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  coverage:
    name: Run test suite for Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Sync coverage w/CodeCov
        env:
          CTOKEN: ${{ secrets.CTOKEN }}
        run: make docker-coverage
