name: Go
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        go-version: ["1.18", "1.19"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: make docker-test
      # - name: Run tests with GC pressure
      #   run: go test github.com/PacketHelper/goshark/v2/goshark -count=1
      #   env:
      #     GOGC: 1
      - name: Run tests with race detector
        run: go test -v -race github.com/PacketHelper/goshark/v2/goshark -count=1
  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: setup Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.18
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: Measure coverage
  #       run: make cover
  #     - uses: codecov/codecov-action@v2
  #       with:
  #         fail_ci_if_error: true
  #         verbose: true
